### ISSUE TITLE
WebUI

### ISSUE THREAD

**Issue by JM-Lemmi** [JM-Lemmi/ical-relay#45]
- [x] Setting up E-Mail reminders JM-Lemmi/ical-relay#34 
- [x] Finding public calendars JM-Lemmi/ical-relay-frontend#1 
- [x] Viewing calendar preview
- [ ] Generating customized URLs JM-Lemmi/ical-relay#44

**Comment by JM-Lemmi** [comment]
Use frereit/react-calendar.

- [ ] Add Readme for setup with react-calendar
